[package]
name = "embedded-profiling"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-time = "0.12"
cortex-m = "0.7"
once_cell = "1.0"
heapless = "0.7"

[dev-dependencies]
std-embedded-time = "0.1"