[workspace]
members = [
    "embedded-profiling",
    "embedded-profiling-proc-macros",
    "embedded-profiling-examples",
]

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 'z'
