[package]
name = "embedded-profiling"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-time = "0.12"
cortex-m = "0.7"
embedded-profiling-proc-macros = { path = "../embedded-profiling-proc-macros", version = "0.1" }

[dev-dependencies]
once_cell = "1.0"
std-embedded-time = "0.1"
