[package]
name = "embedded-profiling"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
fugit = "0.2"
cortex-m = "0.7"
embedded-profiling-proc-macros = { path = "../embedded-profiling-proc-macros", version = "0.1", optional = true }

[dev-dependencies]
once_cell = "1.0"

[features]
default = ["container-u32"]
proc-macros = ["embedded-profiling-proc-macros"]
container-u32 = []
container-u64 = []
