[package]
name = "embedded-profiling"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-time = "0.12"
cortex-m = "0.7"

feather_m4 = { git = "https://github.com/atsamd-rs/atsamd/", features = ["usb", "unproven", "rt"], optional = true }

[dev-dependencies]
once_cell = "1.0"
std-embedded-time = "0.1"
