[package]
name = "embedded-profiling"
description = "Profiling for `no-std` embedded targets"
version = "0.1.5"
edition = "2021"
repository = "https://github.com/TDHolmes/embedded-profiling"
keywords = ["performance", "profiling", "no-std"]
categories = ["development-tools::profiling", "embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
fugit = "0.2"
cortex-m = "0.7"
log = {version = "0.4", optional = true}
embedded-profiling-proc-macros = { path = "../embedded-profiling-proc-macros", version = "0.1", optional = true }

[features]
default = ["container-u32"]
proc-macros = ["embedded-profiling-proc-macros"]
dwt-systick = ["log"]
container-u32 = []
container-u64 = []

[package.metadata.docs.rs]
all-features = true
