
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust (thumbv7em)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf
        components: clippy

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Build embedded-profiling
      run: cargo build --manifest-path ./embedded-profiling/Cargo.toml --all-features

    - name: embedded-profiling clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path ./embedded-profiling/Cargo.toml
        name: embedded-profiling Clippy

    - name: Build embedded-profiling-examples
      run: cargo build --manifest-path ./embedded-profiling-examples/Cargo.toml --all-features

    - name: embedded-profiling-examples clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path ./embedded-profiling-examples/Cargo.toml
        name: embedded-profiling-examples Clippy
