
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust (thumbv7em)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf
        components: clippy, rustfmt

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: install cargo-msrv
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-msrv
        use-tool-cache: true

    - name: Verify MSRV
      run: |
        cargo msrv --verify --path ./embedded-profiling -- cargo check
        cargo msrv --verify --path ./embedded-profiling-proc-macros -- cargo check
        cargo msrv --verify --path ./ep-pin-toggle -- cargo check
        cargo msrv --verify --path ./ep-systick -- cargo check
        cargo msrv --verify --path ./ep-dwt -- cargo check

    - name: Check Formatting
      run: cargo fmt --check

    - name: Build (default)
      env:
        CARGO_BUILD_TARGET: thumbv7em-none-eabihf
        RUSTFLAGS: -D warnings
      run: cargo build

    - name: Build (all features)
      env:
        CARGO_BUILD_TARGET: thumbv7em-none-eabihf
        RUSTFLAGS: -D warnings
      run: cargo build --all-features

    - name: test all crates
      env:
        RUSTFLAGS: -D warnings
      run: cargo test --exclude embedded-profiling-examples --workspace

    - name: Clippy
      env:
        CARGO_BUILD_TARGET: thumbv7em-none-eabihf
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: embedded-profiling Clippy
        args: --all-features -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo -A clippy::must_use_candidate
