
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_TARGET: thumbv7em-none-eabihf

    steps:
    - name: Install Rust (thumbv7em)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf
        components: clippy

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Build (default)
      run: RUSTFLAGS="-D warnings" cargo build

    - name: Build (all features)
      run: RUSTFLAGS="-D warnings" cargo build --all-features

    - name: test embedded-profiling
      run: RUSTFLAGS="-D warnings" cargo test --manifest-path ./embedded-profiling/Cargo.toml

    - name: test embedded-profiling-proc-macros
      run: RUSTFLAGS="-D warnings" cargo test --manifest-path ./embedded-profiling-proc-macros/Cargo.toml

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: embedded-profiling Clippy
        args: --all-features -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo -A clippy::must_use_candidate
