
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_TARGET: thumbv7em-none-eabihf

    steps:
    - name: Install Rust (thumbv7em)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf
        components: clippy

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Verify MSRV
      run: |
        cargo install cargo-msrv
        cargo msrv --bisect --path ./embedded-profiling -- cargo check --workspace --exclude embedded-profiling-examples

    - name: Build (default)
      run: RUSTFLAGS="-D warnings" cargo build

    - name: Build (all features)
      run: RUSTFLAGS="-D warnings" cargo build --all-features

    - name: test all crates
      run: unset CARGO_BUILD_TARGET && RUSTFLAGS="-D warnings" cargo test --exclude embedded-profiling-examples --workspace

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: embedded-profiling Clippy
        args: --all-features -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo -A clippy::must_use_candidate
